# Generated by Django 5.0.3 on 2024-04-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='college',
            field=models.CharField(max_length=255),
        ),
    ]
